
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: nginxsp-v1
  name: nginxsp-v1
spec:
  replicas: 1
  selector:
    name: nginxsp
  template:
    metadata:
      labels: 
        name: nginxsp
        version: v1
    spec:
      containers:
        - name: nginxsp
          image: jordic/nginxsp:v1
          resources:
            limits:
              cpu: 10m
              memory: 50Mi
