
apiVersion: v1
kind: Service
metadata:
  labels:
    name: nginx-proxy
  name: nginx-proxy
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    nodePort: 31950
  selector:
    name: nginxsp
